DESCRIBE TABLE SUPERMARKET_FORECASTING.PUBLIC.TIME_SERIES;

--1. Previewing the data
SELECT *
FROM SUPERMARKET_FORECASTING.PUBLIC.TIME_SERIES
ORDER BY DATE
LIMIT 20;

--2. Comparing Actual vs Predicted Values
SELECT
    DATE,
    ACTUAL,
    ARIMA_PRED,
    SARIMA_PRED,
    EXP_SMOOTH_PRED,
    HW_PRED
FROM SUPERMARKET_FORECASTING.PUBLIC.TIME_SERIES
ORDER BY DATE;

--3. Calculating Prediction Errors
SELECT
    DATE,
    ABS(ACTUAL - ARIMA_PRED) AS ARIMA_ERROR,
    ABS(ACTUAL - SARIMA_PRED) AS SARIMA_ERROR,
    ABS(ACTUAL - EXP_SMOOTH_PRED) AS EXP_SMOOTH_ERROR,
    ABS(ACTUAL - HW_PRED) AS HW_ERROR
FROM SUPERMARKET_FORECASTING.PUBLIC.TIME_SERIES
ORDER BY DATE;

--4. Mean Absolute Error (MAE) for Each Model
SELECT
    ROUND(AVG(ABS(ACTUAL - ARIMA_PRED)), 4) AS MAE_ARIMA,
    ROUND(AVG(ABS(ACTUAL - SARIMA_PRED)), 4) AS MAE_SARIMA,
    ROUND(AVG(ABS(ACTUAL - EXP_SMOOTH_PRED)), 4) AS MAE_EXP_SMOOTH,
    ROUND(AVG(ABS(ACTUAL - HW_PRED)), 4) AS MAE_HOLT_WINTERS
FROM SUPERMARKET_FORECASTING.PUBLIC.TIME_SERIES;

--5. Root Mean Squared Error (RMSE)
SELECT
    ROUND(SQRT(AVG(POWER(ACTUAL - ARIMA_PRED, 2))), 4) AS RMSE_ARIMA,
    ROUND(SQRT(AVG(POWER(ACTUAL - SARIMA_PRED, 2))), 4) AS RMSE_SARIMA,
    ROUND(SQRT(AVG(POWER(ACTUAL - EXP_SMOOTH_PRED, 2))), 4) AS RMSE_EXP_SMOOTH,
    ROUND(SQRT(AVG(POWER(ACTUAL - HW_PRED, 2))), 4) AS RMSE_HOLT_WINTERS
FROM SUPERMARKET_FORECASTING.PUBLIC.TIME_SERIES;

--6. Identifying the Best Performing Model
WITH model_errors AS (
    SELECT 'ARIMA' AS MODEL, AVG(ABS(ACTUAL - ARIMA_PRED)) AS MAE
    FROM SUPERMARKET_FORECASTING.PUBLIC.TIME_SERIES
    UNION ALL
    SELECT 'SARIMA', AVG(ABS(ACTUAL - SARIMA_PRED))
    FROM SUPERMARKET_FORECASTING.PUBLIC.TIME_SERIES
    UNION ALL
    SELECT 'EXPONENTIAL SMOOTHING', AVG(ABS(ACTUAL - EXP_SMOOTH_PRED))
    FROM SUPERMARKET_FORECASTING.PUBLIC.TIME_SERIES
    UNION ALL
    SELECT 'HOLT-WINTERS', AVG(ABS(ACTUAL - HW_PRED))
    FROM SUPERMARKET_FORECASTING.PUBLIC.TIME_SERIES
)
SELECT *
FROM model_errors
ORDER BY MAE;

--7. Monthly Trend Analysis
SELECT
    YEAR(DATE) AS YEAR,
    MONTH(DATE) AS MONTH,
    AVG(ACTUAL) AS AVG_ACTUAL,
    AVG(ARIMA_PRED) AS AVG_ARIMA,
    AVG(SARIMA_PRED) AS AVG_SARIMA,
    AVG(EXP_SMOOTH_PRED) AS AVG_EXP_SMOOTH,
    AVG(HW_PRED) AS AVG_HW
FROM SUPERMARKET_FORECASTING.PUBLIC.TIME_SERIES
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH;

--8. Creating a View for Power BI Dashboards
CREATE OR REPLACE VIEW SUPERMARKET_FORECASTING.PUBLIC.TIME_SERIES_DASHBOARD AS
SELECT
    DATE,
    ACTUAL,
    ARIMA_PRED,
    SARIMA_PRED,
    EXP_SMOOTH_PRED,
    HW_PRED,
    ABS(ACTUAL - ARIMA_PRED) AS ARIMA_ERROR,
    ABS(ACTUAL - SARIMA_PRED) AS SARIMA_ERROR,
    ABS(ACTUAL - EXP_SMOOTH_PRED) AS EXP_SMOOTH_ERROR,
    ABS(ACTUAL - HW_PRED) AS HW_ERROR
FROM SUPERMARKET_FORECASTING.PUBLIC.TIME_SERIES;

SELECT * 
FROM SUPERMARKET_FORECASTING.PUBLIC.TIME_SERIES_DASHBOARD;

--9. Calculating Forecast Accuracy (%)
SELECT
    ROUND(100 - AVG(ABS(ACTUAL - ARIMA_PRED) / ACTUAL) * 100, 2) AS ARIMA_ACCURACY,
    ROUND(100 - AVG(ABS(ACTUAL - SARIMA_PRED) / ACTUAL) * 100, 2) AS SARIMA_ACCURACY,
    ROUND(100 - AVG(ABS(ACTUAL - EXP_SMOOTH_PRED) / ACTUAL) * 100, 2) AS EXP_SMOOTH_ACCURACY,
    ROUND(100 - AVG(ABS(ACTUAL - HW_PRED) / ACTUAL) * 100, 2) AS HW_ACCURACY
FROM SUPERMARKET_FORECASTING.PUBLIC.TIME_SERIES
WHERE ACTUAL <> 0;

--10. Find the Date with Maximum Forecast Error
SELECT
    DATE,
    ACTUAL,
    HW_PRED,
    ABS(ACTUAL - HW_PRED) AS MAX_ERROR
FROM SUPERMARKET_FORECASTING.PUBLIC.TIME_SERIES
ORDER BY MAX_ERROR DESC
LIMIT 10;

SELECT *
FROM SUPERMARKET_FORECASTING.PUBLIC.TIME_SERIES;